name: Secasign SDK workflow
on: [push]
jobs:
    Secasign-SDK-Workflow:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java-version: [8, 11, 17, 21]
        steps:
            - name: Clone the repository
              uses: actions/checkout@v4
            - name: Encode and write the configuration properties
              run: echo "${{ secrets.ENCODED_CONFIGURATION_PROPERTIES }}" | base64 -d > configuration.properties
            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  java-version: ${{ matrix.java-version }}
                  distribution: 'temurin'
            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3
            - name: Setup C#
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '8.x'
            - name: Build and test the Java project
              run: ./gradlew build
              working-directory: java
            - name: Install the C# dependencies
              run: dotnet restore
              working-directory: csharp
            - name: Build the C# solution
              run: dotnet build
              working-directory: csharp
            - name: Test the C# solution
              run: dotnet test
              working-directory: csharp
